# Generated by Django 3.0.8 on 2020-07-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_backendLanguage',
            field=models.CharField(default='Java', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='project_summary',
            field=models.CharField(default='this is the default summary', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(max_length=30),
        ),
    ]
