# Generated by Django 3.0.8 on 2020-07-31 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200726_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison_Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('projectA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ComparedAsA', to='projects.Projects')),
                ('projectB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ComparedAsB', to='projects.Projects')),
            ],
        ),
    ]
