# Generated by Django 3.0.8 on 2020-08-04 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200731_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison_pair',
            name='countA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comparison_pair',
            name='countB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comparison_pair',
            name='r1Aw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comparison_pair',
            name='r1Bw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comparison_pair',
            name='r2Aw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comparison_pair',
            name='r2Bw',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Projects')),
            ],
        ),
    ]
